name: Szy

on:
  workflow_dispatch:

jobs:
  setup-machines:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 saat (hesabın izin verirse)
    strategy:
      matrix:
        machine: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]
    steps:
      - name: Show system info
        run: |
          echo "CPU Info:"
          lscpu
          echo "RAM Info:"
          free -h
          echo "Disk Info:"
          df -h

      - name: Install tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Start 10 tmate sessions
        run: |
          for i in {1..10}; do
            tmate -S /tmp/tmate_$i.sock new-session -d
            tmate -S /tmp/tmate_$i.sock wait tmate-ready
            echo "Makine ${{ matrix.machine }} - tmate $i SSH: $(tmate -S /tmp/tmate_$i.sock display -p '#{tmate_ssh}')"
          done

      - name: Keep session running
        run: |
          echo "Makine ${{ matrix.machine }} 24 saat boyunca açık kalacak..."
          sleep 86400
