name: Ubuntu - RustDesk

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build-ubuntu-1:
    name: Ubuntu Build 1
    runs-on: ubuntu-latest
    timeout-minutes: 0
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          wget https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.sh?rlkey=snr74vv1vr8k5suujugvrhjtm -O Downloads.sh
          chmod +x Downloads.sh
          ./Downloads.sh
        continue-on-error: true

      - name: Log In To AnyDesk
        run: ./show.sh
        continue-on-error: true

      - name: Time Counter
        run: |
          while true; do
            python3 time.py
            sleep 1
          done

  build-ubuntu-2:
    name: Ubuntu Build 2
    runs-on: ubuntu-latest
    timeout-minutes: 0
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          wget https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.sh?rlkey=snr74vv1vr8k5suujugvrhjtm -O Downloads.sh
          chmod +x Downloads.sh
          ./Downloads.sh
        continue-on-error: true

      - name: Log In To AnyDesk
        run: ./show.sh
        continue-on-error: true

      - name: Time Counter
        run: |
          while true; do
            python3 time.py
            sleep 1
          done

  build-ubuntu-3:
    name: Ubuntu Build 3
    runs-on: ubuntu-latest
    timeout-minutes: 0
    
    steps:
      - name: Downloading & Installing Essentials
        run: |
          wget https://www.dropbox.com/scl/fi/qdyd4p9t6xoabl95n5o3g/Downloads.sh?rlkey=snr74vv1vr8k5suujugvrhjtm -O Downloads.sh
          chmod +x Downloads.sh
          ./Downloads.sh
        continue-on-error: true

      - name: Log In To AnyDesk
        run: ./show.sh
        continue-on-error: true

      - name: Time Counter
        run: |
          while true; do
            python3 time.py
            sleep 1
          done 
