name: Szy

on:
  workflow_dispatch:

jobs:
  setup-machines:
    runs-on: ubuntu-latest
    timeout-minutes: 1440  # 24 saat (hesabın izin verirse)
    strategy:
      matrix:
        machine: [1,2,3,4,5,6,7,8,9,10]
    steps:
      - name: Show system info
        run: |
          echo "CPU Info:"
          lscpu
          echo "RAM Info:"
          free -h
          echo "Disk Info:"
          df -h

      - name: Install tmate
        run: sudo apt-get update && sudo apt-get install -y tmate

      - name: Start tmate session
        id: tmate
        run: |
          tmate -S /tmp/tmate.sock new-session -d
          tmate -S /tmp/tmate.sock wait tmate-ready
          echo "Makine ${{ matrix.machine }} SSH: $(tmate -S /tmp/tmate.sock display -p '#{tmate_ssh}')"

      - name: Keep session running
        run: |
          echo "Makine ${{ matrix.machine }} 24 saat boyunca açık kalacak..."
          sleep 86400  # 24 saat bekle
